const texts = [
    "La psychologie est l'étude de l'esprit, des émotions et du comportement humains, ainsi que des relations complexes qui nous influencent au quotidien. Comprendre ces dynamiques nous aide à mieux appréhender notre réalité et à naviguer dans nos interactions.", // citation n°1
    "L'art est une forme d'expression qui touche les sens et évoque des réactions uniques. Il nous transporte à travers des mélodies, des couleurs et des formes qui défient les conventions culturelles et interpellent notre âme.", // citation n°2
    "La sociologie examine les rapports humains au sein des sociétés contemporaines, mettant en lumière comment la culture et les normes façonnent notre comportement ainsi que nos choix de vie au quotidien.", // citation n°3
    "La musique possède le pouvoir d'influencer nos émotions, de créer des souvenirs profonds et de transformer les ambiances au sein de nos vies. Les compositeurs et les paroles touchent notre esprit et évoquent des moments nostalgiques.", // citation n°4
    "L'éducation est la clé des opportunités dans notre monde moderne. Elle favorise la connaissance, la compréhension et l'esprit critique, ouvrant des portes vers l'autonomie et l'inclusion de chacun à travers des valeurs fondamentales.", // citation n°5
    "La nature nous rappelle la beauté du monde vivant avec ses paysages diversifiés, ses animaux fascinants et les écosystèmes qui interagissent. Elle nous enseigne des leçons sur la patience, le respect et l'harmonie à travers ses cycles.", // citation n°6
    "L'amour est un sentiment complexe, constitué de passion, d'engagement et de partage réel. Une véritable aventure humaine pleine de joies et de défis quotidiens qui enrichit notre existence.", // citation n°7
    "La technologie redéfinit nos vies à travers des outils de communication et d'information. Elle nous offre de nouvelles possibilités tout en soulevant des questions éthiques qui méritent d'être examinées en profondeur.", // citation n°8
    "La bienveillance est une valeur fondamentale dans nos relations humaines, nous rappelant l'importance de l'empathie, de la compassion et de l'écoute attentive envers autrui pour créer des liens sacrés.", // citation n°9
    "Le sport est un excellent moyen de développer la discipline, la confiance et la cohésion. Pratiquer une activité physique peut non seulement améliorer notre santé physique mais également notre bien-être mental." // citation n°10
];