const title = "application « compléter »";
const subtitle = "réviser en complétant un texte à trous";
const textesAvecTrous = [
// texte n°1 //
	{ texte: "Lorem **mots manquants 1** sit amet, **mots manquants 2** elit, sed do **mots manquants 3** incididunt ut labore et dolore **mots manquants 4**. Ut enim ad **mots manquants 5**, quis nostrud exertexte ullamco **mots manquants 6** laboris nisi ut aliquip ex ea **mots manquants 7** commodo consequat. Duis aute irure dolor in reprehenderit in **mots manquants 8** esse cillum **mots manquants 9** dolore eu fugiat nulla **mots manquants 10** pariatur. Excepteur sint occaecat **mots manquants 11** cupidatat non proident, sunt in culpa qui officia **mots manquants 12** deserunt mollit anim id est laborum.", source: "Prénom1 NOM1, Titre, p.XXX" },
// texte n°2 //
	{ texte: "At **mots manquants 1** et accusamus et iusto odio **mots manquants 2** qui blanditiis praesentium **mots manquants 3** atque corrupti quos dolores et quas molestias **mots manquants 4** excepturi sint occaecati **mots manquants 5** cupiditate non provident. Similique sunt in **mots manquants 6** culpa qui officia deserunt mollitia animi, id est **mots manquants 7** fuga. Et **mots manquants 8** rerum facilis est et expedita distinctio. Nam **mots manquants 9**, cum soluta **mots manquants 10** nobis est eligendi optio **mots manquants 11** cumque nihil impedit quo minus **mots manquants 12** id quod maxime placeat facere possimus.", source: "Prénom2 NOM2, Titre, p.YYY" },
// texte n°3 //
	{ texte: "Temporibus **mots manquants 1** et aut officiis **mots manquants 2** necessitatibus saepe eveniet ut **mots manquants 3** et voluptates repudiandae sint et **mots manquants 4** molestiae non recusandae. Itaque **mots manquants 5** earum rerum hic tenetur a **mots manquants 6**, ut aut reiciendis voluptatibus maiores alias **mots manquants 7** consequatur aut perferendis **mots manquants 8** doloribus asperiores repellat. Ut enim ad **mots manquants 9**, quis nostrum exertexteem **mots manquants 10** suscipit laboriosam, nisi **mots manquants 11** ut aliquid ex **mots manquants 12** consequatur ?", source: "Prénom3 NOM3, Titre, p.ZZZ" }
];
if (typeof module !== 'undefined') module.exports = { title, subtitle, textesAvecTrous };
